#!/bin/bash

FILES=${1:-"$HOME/dotfiles"}
DMENU='dmenu -l -i'
EDITOR='alacritty -e vim'

# show list of options
choice=$(ls -a "${FILES}" | $DMENU -p "File to edit:")

if [ $choice ]; then
    $EDITOR ${FILES}/${choice}
fi
