[ -f ~/.zshrc ] && . ~/.zshrc

GOBIN="/usr/local/go/bin"
GOROOT="/usr/local/go"
NVIM_PATH="/usr/local/nvim/bin"
LOCAL_BIN_PATH="$HOME/.local/bin"
CARGO_PATH="$HOME/.cargo/bin"
GHC_PATH="$HOME/.ghcup/bin"
ORACLE_SQL_PATH="/usr/local/bin/osql/bin"
BREW_PATH="/opt/homebrew/bin"
export PATH="$BREW_PATH:$GHC_PATH:$GOBIN:$GOROOT:$NVIM_PATH:$LOCAL_BIN_PATH:$CARGO_PATH:$ORACLE_SQL_PATH:$HOME/bin:/usr/local/bin:$PATH"

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
	exec startx
fi
