# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Path to custom plugins folder
export ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8
export VISUAL='nvim'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

function echo_git_ignore() {
    echo $1 >> ".gitignore"
}

# aliases
alias gpf="git push --force"
alias egig="echo_git_ignore"
alias gdec="git log --decorate=full --oneline --graph"
alias nvconfig="cd $HOME/dotfiles/nvim && nvim"
alias l="ls -halF"
alias gdec="git log --decorate=full --oneline --graph"
alias nvconfig="cd $HOME/dotfiles/nvim && nvim"
alias nv-notes="cd $HOME/ReadingNotes && nvim"
alias glg='git log --oneline --decorate --graph'
alias grf="git reflog"
alias gl="git pull"
alias ga="git add"
alias gp="git push"
alias gpsup="git push -u"
alias gfa="git fetch -a"
alias gb="git branch"
alias gst="git status"
alias gd="git diff"
alias gc="git commit"
alias gcam="gc -am"
alias gcb="git checkout -b"
alias gsw="git switch"
alias grb="git rebase"
alias grbi="git rebase --interactive"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias dcb="docker compose --build"
alias dcud="dcb -d"
alias gco="git checkout"
alias grs="git reset"

# neovim variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export LOCAL_PLUGINS_HOME="$HOME/Projects/nvim-plugins/"
export REACT_EDITOR="none"
alias nv="nvim"
# dive docker inspection
alias dive="docker run -ti --rm  -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive"

# node env variable
function lazy_load_nvm() {
    unset -f node nvm npm
    export NVM_DIR="$XDG_CONFIG_HOME/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}

function node() {
    lazy_load_nvm
    node $@
}

function npm() {
    lazy_load_nvm
    npm $@
}

function nvm() {
    lazy_load_nvm
    nvm $@
}

lazy_load_nvm

[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env

# Prompt
function git_branch_cmd() {
    echo "$(git branch 2>/dev/null | grep '*' | colrm 1 2)"
}
setopt PROMPT_SUBST
export PS1='%{%F{109}%}%n %{%F{106}%}$(git_branch_cmd) %{%F{72}%}%1~ %{%F{96}%}λ %{%f%}'
