# Set path environment variables ONCE
GOBIN="/usr/local/go/bin"
GOROOT="/usr/local/go"
NVIM_PATH="/usr/local/nvim/bin"
LOCAL_BIN_PATH="$HOME/.local/bin"
CARGO_PATH="$HOME/.cargo/bin"
#JAVA_PATH="/usr/local/opt/openjdk@17/bin"
GHC_PATH="$HOME/.ghcup/bin"
ORACLE_SQL_PATH="/usr/local/bin/osql/bin"
BREW_PATH="/opt/homebrew/bin"

export PATH="$BREW_PATH:$GHC_PATH:$GOBIN:$GOROOT:$NVIM_PATH:$LOCAL_BIN_PATH:$CARGO_PATH:$ORACLE_SQL_PATH:$HOME/bin:/usr/local/bin:$PATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk17"

source /Users/plharvey/.bashrc

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in
    *:/Users/plharvey/.juliaup/bin:*)
        ;;

    *)
        export PATH=/Users/plharvey/.juliaup/bin${PATH:+:${PATH}}
        ;;
esac

# <<< juliaup initialize <<<
