# If you come from bash you might have to change your $PATH.
GOBIN="/usr/local/go/bin"
export GOBIN=$GOBIN
GOROOT="/usr/local/go"
NVIM_PATH="/usr/local/nvim/bin"
LOCAL_BIN_PATH="$HOME/.local/bin"
CARGO_PATH="$HOME/.cargo/bin"
JAVA_PATH="/usr/local/opt/openjdk@17/bin"
GHC_PATH="$HOME/.ghcup/bin"
export PATH="$GHC_PATH:$JAVA_PATH:$GOBIN:$GOROOT:$NVIM_PATH:$LOCAL_BIN_PATH:$CARGO_PATH:$ORACLE_SQL_PATH:$HOME/bin:/usr/local/bin:$PATH"
export GOPATH="$HOME/go"

# User configuration
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias gdec="git log --decorate=full --oneline --graph"
alias nvconfig="cd $HOME/dotfiles/nvim && nvim"
alias nv-notes="cd $HOME/ReadingNotes && nvim"
alias lsd="ls -halF"
alias l="lsd"
alias gl="git pull"
alias gp="git push"
alias gpsup="git push -u"
alias gfa="git fetch -a"
alias gb="git branch"
alias gst="git status"
alias gd="git diff"
alias gc="git commit"
alias gcam="gc -am"
alias gcb="git checkout -b"

export NV_NOTES_PATH="$HOME/Notes"

# neovim variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export LOCAL_PLUGINS_HOME="$HOME/Projects/nvim-plugins/"
export REACT_EDITOR="none"
alias nv="nvim"

# node env variable
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
